name = input("enter your name:")
city = input("ener your city:")
fav_food = input("enter your favourite food:")
fav_hobbies = input("enter your favourite hobby:")
fav_color = input("enter your favourite color:")
fav_actor = input("enter your favourite actor:")
fav_movie = input("enter your favourite movie:")
fav_author = input("enter your favourite author:")
fav_song = input("enter your favourite song:")
fav_subject = input("enter your favourite subject:")
print("!!!!INFO!!!!")
print(f'{name=}')
print(f'{city=}')
print(f'{fav_food=}')
print(f'{fav_hobbies=}')
print(f'{fav_color=}')
print(f'{fav_actor=}')
print(f'{fav_movie=}')
print(f'{fav_author=}')
print(f'{fav_song=}')
print(f'{fav_subject=}')
print("!!!!INFO!!!!")